// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Demo")]
[assembly: AssemblyProductAttribute("Demo")]
[assembly: AssemblyDescriptionAttribute("This is just a demo")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.1";
    }
}
