// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("PasswordValidator")]
[assembly: AssemblyProductAttribute("PasswordValidator")]
[assembly: AssemblyDescriptionAttribute("A demo project that implements a simple password validation library")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
