#I "."
#I "../packages/MBrace.Azure.Standalone/tools"
#I "../packages/Streams/lib/net45"
#I "../packages/MBrace.Flow/lib/net45"
#r "../packages/Streams/lib/net45/Streams.Core.dll"
#r "../packages/MBrace.Flow/lib/net45/MBrace.Flow.dll"
#load "../packages/MBrace.Azure.Standalone/MBrace.Azure.fsx"
